remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Página de exemplo para o curso REA e licenças CC]
description: [Apenas uma página de exemplo, ok?]
